services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - dad-jokes-network
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dad-jokes-network
    restart: always

networks:
  dad-jokes-network:
    driver: bridge

volumes:
  mongodb_data: 